<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="wave.txt" />
    <None Remove="wave.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFMediaToolkit" Version="4.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OscillographPlayer.WaveGenerateLib\OscillographPlayer.WaveGenerateLib.csproj" />
    <ProjectReference Include="..\OscillographPlayer\OscillographPlayer.csproj" />
  </ItemGroup>

  <Target Name="CopyWaveGenerateCore" AfterTargets="Build">
  	<Copy SourceFiles="$(SolutionDir)bin\$(Configuration)\OscillographPlayer.WaveGenerateCore.dll" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" Condition="Exists('$(SolutionDir)bin\$(Configuration)\OscillographPlayer.WaveGenerateCore.dll')" />
    <Copy SourceFiles="$(SolutionDir)bin\$(Configuration)\OscillographPlayer.WaveGenerateCore.pdb" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" Condition="Exists('$(SolutionDir)bin\$(Configuration)\OscillographPlayer.WaveGenerateCore.pdb')" />
  </Target>

</Project>
